"""changed_retries_field_to_attempt

Revision ID: 0dbd68b8b4fe
Revises: 1795bf2f6429
Create Date: 2026-04-08 23:43:54.885848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbd68b8b4fe'
down_revision: Union[str, Sequence[str], None] = '1795bf2f6429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('attempts', sa.Integer(), nullable=False))
    op.drop_column('job', 'retries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('job', 'attempts')
    # ### end Alembic commands ###
