"""set_google_id_field_to_optional

Revision ID: 1795bf2f6429
Revises: fa6228b9f261
Create Date: 2026-03-17 00:17:03.570851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1795bf2f6429'
down_revision: Union[str, Sequence[str], None] = 'fa6228b9f261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
