"""added_lease_fields_to_jobs

Revision ID: 652a46f43e3f
Revises: 1795bf2f6429
Create Date: 2026-03-25 00:37:22.169947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '652a46f43e3f'
down_revision: Union[str, Sequence[str], None] = '1795bf2f6429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('lease_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('failed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'failed_at')
    op.drop_column('job', 'completed_at')
    op.drop_column('job', 'started_at')
    op.drop_column('job', 'last_heartbeat_at')
    op.drop_column('job', 'lease_token')
    op.drop_column('job', 'lease_expires_at')
    # ### end Alembic commands ###
