"""added_available_at_field

Revision ID: 6d046513d55a
Revises: 0dbd68b8b4fe
Create Date: 2026-04-08 23:52:35.896652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d046513d55a'
down_revision: Union[str, Sequence[str], None] = '0dbd68b8b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('available_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'available_at')
    # ### end Alembic commands ###
