"""create service_table_and_edit_jobs_table

Revision ID: 7dff373df09d
Revises: 1ed93dc4c844
Create Date: 2026-03-16 15:01:51.694044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dff373df09d'
down_revision: Union[str, Sequence[str], None] = '1ed93dc4c844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


jobstatus_enum = postgresql.ENUM(
    "QUEUED", "RUNNING", "COMPLETED", "FAILED", name="jobstatus"
)
jobpriority_enum = postgresql.ENUM(
    "LOW", "MEDIUM", "HIGH", name="jobpriority"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    jobstatus_enum.create(bind, checkfirst=True)
    jobpriority_enum.create(bind, checkfirst=True)

    op.create_table('service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('EMAIL', name='nameofservices'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('job', 'status',
               existing_type=sa.VARCHAR(),
               type_=jobstatus_enum,
               nullable=True,
               postgresql_using='upper(status)::jobstatus')
    op.alter_column('job', 'priority',
               existing_type=sa.VARCHAR(),
               type_=jobpriority_enum,
               nullable=True,
               postgresql_using='upper(priority)::jobpriority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'priority',
               existing_type=jobpriority_enum,
               type_=sa.VARCHAR(),
               nullable=False,
               postgresql_using='lower(priority::text)')
    op.alter_column('job', 'status',
               existing_type=jobstatus_enum,
               type_=sa.VARCHAR(),
               nullable=False,
               postgresql_using='lower(status::text)')
    op.drop_table('service')

    bind = op.get_bind()
    jobpriority_enum.drop(bind, checkfirst=True)
    jobstatus_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
