"""add_cancelled_status_and_perf_indexes

Revision ID: 88345ce9e847
Revises: d3f1882084f6
Create Date: 2026-05-21 16:28:56.735306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88345ce9e847'
down_revision: Union[str, Sequence[str], None] = 'd3f1882084f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_job_status_scheduled'), table_name='job')
    op.create_index('idx_job_status_available', 'job', ['status', 'available_at'], unique=False)
    op.create_index('idx_job_status_lease', 'job', ['status', 'lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_status_lease', table_name='job')
    op.drop_index('idx_job_status_available', table_name='job')
    op.create_index(op.f('idx_job_status_scheduled'), 'job', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###
